name: sohoj_kart
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

#................Packages...........................#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # -- For http connection
  http: ^1.2.0

  # -- For Date and Time format
  intl: ^0.18.1

  logger: ^2.0.2+1
  lottie: ^3.1.0
  url_launcher: ^6.2.4
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0
  device_preview: ^1.1.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  #Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  #Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.10

#..............Packages End........................#




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/icons/lottie/
    - assets/images/
    - assets/logos/
    - assets/images/on_boarding_image/
    - assets/images/animations/
    - assets/images/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/cloths/


      #categories
    - assets/images/categories/
    - assets/images/categories/electronics/
    - assets/images/categories/sports/
    - assets/images/categories/furniture/




  fonts:
    -  family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Light.ttf
           weight: 300
         - asset: assets/fonts/Poppins-Regular.ttf
           weight: 400
         - asset: assets/fonts/Poppins-Italic.ttf
           style: italic
         - asset: assets/fonts/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/Poppins-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/fonts/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 800
